import type { SiteService, SiteServiceIconKey } from "@/lib/db/models"

type ServiceSeed = Omit<SiteService, "_id" | "createdAt" | "updatedAt" | "updatedBy">

function svc(
  slug: string,
  title: string,
  icon: SiteServiceIconKey,
  colorGradient: string,
  shortDescription: string,
  features: string[],
  overviewTitle: string,
  overviewParagraphs: string[],
  processSteps: { title: string; description: string }[],
  workCategories: { title: string; description?: string; items: string[] }[],
  benefits: string[],
  order: number,
): ServiceSeed {
  return {
    slug,
    title,
    icon,
    colorGradient,
    shortDescription,
    features,
    overviewTitle,
    overviewParagraphs,
    processSteps: processSteps.map((s, i) => ({ ...s, order: i + 1 })),
    workCategories,
    benefits,
    heroImage: "",
    heroImageAlt: `${title} — EMPRENOR Construcciones`,
    gallery: [],
    published: true,
    order,
  }
}

export const SITE_SERVICE_DEFAULTS: ServiceSeed[] = [
  svc(
    "construccion",
    "Construcción",
    "Building2",
    "from-blue-500 to-blue-600",
    "Construimos proyectos residenciales, comerciales e industriales con los más altos estándares de calidad, seguridad y eficiencia en el NOA.",
    ["Viviendas unifamiliares", "Edificios comerciales", "Obras públicas", "Estructuras metálicas"],
    "Construcción Profesional",
    [
      "En EMPRENOR ofrecemos servicios integrales de construcción desde la planificación inicial hasta la entrega final. Nuestro equipo se encarga de cada detalle para garantizar que su proyecto se complete a tiempo, dentro del presupuesto y con la máxima calidad.",
      "Operamos en Salta, Jujuy, Tucumán y Formosa con equipos especializados en construcción, remodelación e instalaciones.",
    ],
    [
      { title: "Consulta y Planificación", description: "Reunión inicial, análisis del sitio, estudios de factibilidad, costos y cronogramas preliminares." },
      { title: "Diseño y Permisos", description: "Planos arquitectónicos y estructurales, gestión de permisos y aprobaciones municipales." },
      { title: "Preparación del Sitio", description: "Nivelación, excavaciones, cimentaciones, servicios temporales y medidas de seguridad." },
      { title: "Construcción de Estructura", description: "Cimientos, estructura de hormigón y/o acero, muros y techos con inspecciones de calidad." },
      { title: "Instalaciones y Acabados", description: "Sistemas eléctricos, hidráulicos, sanitarios, pisos, revestimientos y pintura." },
      { title: "Inspección Final y Entrega", description: "Inspección exhaustiva, limpieza, documentación, garantías y capacitación al cliente." },
    ],
    [
      { title: "Construcción Residencial", items: ["Casas unifamiliares", "Condominios y departamentos", "Desarrollos habitacionales"] },
      { title: "Construcción Comercial", items: ["Oficinas corporativas", "Locales comerciales", "Centros comerciales"] },
      { title: "Construcción Industrial", items: ["Naves industriales", "Bodegas y almacenes", "Plantas de producción"] },
      { title: "Proyectos Especiales", items: ["Instalaciones deportivas", "Instituciones educativas", "Centros de salud"] },
    ],
    ["Personal certificado y ART al día", "Control de calidad en cada etapa", "Cumplimiento normativo IRAM/INTI", "Garantía escrita post-entrega"],
    1,
  ),
  svc(
    "remodelacion",
    "Remodelación",
    "Home",
    "from-purple-500 to-purple-600",
    "Transformamos espacios existentes en ambientes modernos, funcionales y estéticamente superiores con diseño personalizado.",
    ["Remodelación integral", "Ampliaciones", "Refacciones", "Diseño de interiores"],
    "Remodelación y Renovación",
    [
      "Renovamos viviendas, oficinas y locales comerciales respetando la estructura existente y optimizando la funcionalidad del espacio.",
      "Coordinamos todas las especialidades — albañilería, electricidad, plomería y pintura — bajo un único interlocutor para evitar demoras y sobrecostos.",
    ],
    [
      { title: "Relevamiento y Diagnóstico", description: "Visita técnica, mediciones, estado estructural y definición de alcance con el cliente." },
      { title: "Anteproyecto y Presupuesto", description: "Propuesta de diseño, materiales, plazos y presupuesto detallado por partidas." },
      { title: "Demolición Selectiva", description: "Retiro de terminaciones, protección de áreas no intervenidas y gestión de residuos." },
      { title: "Obra Gruesa y Instalaciones", description: "Mampostería, ampliaciones, redes eléctricas, sanitarias y de gas según proyecto." },
      { title: "Terminaciones", description: "Revoques, pisos, carpintería, pintura y detalles de acabado." },
      { title: "Entrega y Postventa", description: "Limpieza final, checklist de entrega y soporte de garantía." },
    ],
    [
      { title: "Viviendas", items: ["Cocinas y baños", "Ampliaciones", "Refuncionalización de ambientes"] },
      { title: "Comercios", items: ["Locales comerciales", "Restaurantes", "Salas de exposición"] },
      { title: "Oficinas", items: ["Espacio abierto", "Salas de reunión", "Accesibilidad"] },
      { title: "Fachadas", items: ["Revitalización exterior", "Aislación térmica", "Señalética"] },
    ],
    ["Obra limpia y ordenada", "Mínima interrupción de actividades", "Materiales de primera línea", "Coordinación integral de gremios"],
    2,
  ),
  svc(
    "albanileria",
    "Albañilería",
    "Hammer",
    "from-orange-500 to-orange-600",
    "Trabajos de albañilería profesional con maestros certificados para proyectos residenciales, comerciales e industriales.",
    ["Mampostería", "Revoques", "Contrapisos", "Estructuras"],
    "Albañilería de Precisión",
    [
      "Realizamos mampostería, revoques, contrapisos y estructuras de hormigón con maestros mayores de obra y oficiales especializados.",
      "Trabajamos en obra nueva, ampliaciones y reparaciones estructurales con estricto control de calidad y cumplimiento de planos.",
    ],
    [
      { title: "Replanteo", description: "Trazado, niveles y control dimensional según planos." },
      { title: "Mampostería", description: "Muros portantes y divisorios con ladrillos cerámicos, bloques o ladrillo visto." },
      { title: "Hormigón", description: "Bases, vigas, losas y escaleras con control de calidad del hormigón." },
      { title: "Revoques", description: "Revoque grueso, fino, exterior e interior con terminación lista para pintar." },
      { title: "Contrapisos", description: "Nivelación, aislación y contrapiso de hormigón o mortero." },
      { title: "Control Final", description: "Plomos, escuadras y entrega conforme a especificaciones." },
    ],
    [
      { title: "Obra nueva", items: ["Muros perimetrales", "Tabiques", "Losas"] },
      { title: "Reparaciones", items: ["Grietas estructurales", "Humedades", "Refuerzos"] },
      { title: "Revoques especiales", items: ["Exterior SIR", "Texturas", "Ladrillo visto"] },
      { title: "Industrial", items: ["Bases de maquinaria", "Canaletas", "Pisos industriales"] },
    ],
    ["Maestros con experiencia comprobada", "Materiales certificados", "Cumplimiento de plomos y niveles", "Integración con resto de gremios"],
    3,
  ),
  svc(
    "electricidad",
    "Electricidad",
    "Lightbulb",
    "from-yellow-500 to-yellow-600",
    "Instalaciones eléctricas seguras, eficientes y certificadas para hogares y empresas con cumplimiento normativo AEA.",
    ["Instalaciones nuevas", "Tableros eléctricos", "Iluminación", "Sistemas trifásicos"],
    "Instalaciones Eléctricas Certificadas",
    [
      "Diseñamos e instalamos sistemas eléctricos residenciales, comerciales e industriales con materiales homologados y personal matriculado.",
      "Realizamos mediciones, puesta a tierra, tableros, iluminación LED y sistemas de respaldo según normativa vigente.",
    ],
    [
      { title: "Proyecto Eléctrico", description: "Cálculo de cargas, diseño de circuitos y selección de protecciones." },
      { title: "Canalización y Cableado", description: "Tendido de caños, bandejas, cables y cajas según plano." },
      { title: "Tableros y Protecciones", description: "Montaje de tableros, disyuntores, térmicas y diferenciales." },
      { title: "Iluminación", description: "Instalación de luminarias, sensores, automatismos y eficiencia energética." },
      { title: "Pruebas y Mediciones", description: "Continuidad, aislamiento, puesta a tierra y protocolo de ensayos." },
      { title: "Certificación", description: "Entrega de plano conforme a obra, certificado de instalación y habilitación." },
    ],
    [
      { title: "Residencial", items: ["Instalación completa", "Ampliaciones", "Reparaciones"] },
      { title: "Comercial", items: ["Locales", "Oficinas", "Cartelería luminosa"] },
      { title: "Industrial", items: ["Trifásica", "Motores", "Subestaciones menores"] },
      { title: "Eficiencia", items: ["LED", "Sensores", "Automatización básica"] },
    ],
    ["Electricistas matriculados", "Materiales AEA homologados", "Mediciones con instrumentación calibrada", "Certificado de instalación"],
    4,
  ),
  svc(
    "plomeria",
    "Plomería",
    "Droplets",
    "from-cyan-500 to-cyan-600",
    "Servicios de plomería completos: instalaciones sanitarias, desagües, agua caliente y mantenimiento preventivo.",
    ["Instalaciones sanitarias", "Desagües cloacales", "Agua caliente", "Reparaciones"],
    "Plomería y Sanitaria",
    [
      "Instalamos y reparamos redes de agua fría, caliente, desagües cloacales y pluviales con materiales de calidad y pruebas de presión.",
      "Atendemos urgencias, refacciones de baños y cocinas, y obras integrales en viviendas y edificios.",
    ],
    [
      { title: "Diagnóstico", description: "Detección de fugas, revisión de instalaciones existentes y relevamiento." },
      { title: "Proyecto Sanitario", description: "Dimensionado de cañerías, ventilaciones y artefactos." },
      { title: "Instalación", description: "Tendido de cañerías, conexiones, artefactos y desagües." },
      { title: "Pruebas Hidráulicas", description: "Prueba de presión, estanqueidad y funcionamiento." },
      { title: "Terminaciones", description: "Sellados, rejillas, griferías y conexiones finales." },
      { title: "Mantenimiento", description: "Planes preventivos y atención de emergencias." },
    ],
    [
      { title: "Agua fría y caliente", items: ["Cañerías", "Termotanques", "Bombas"] },
      { title: "Desagües", items: ["Cloacales", "Pluviales", "Sifones"] },
      { title: "Baños y cocinas", items: ["Artefactos", "Mesadas", "Mamparas"] },
      { title: "Industrial", items: ["Líneas de proceso", "Tanques", "Incendio"] },
    ],
    ["Materiales certificados", "Pruebas de presión documentadas", "Atención de urgencias", "Garantía en mano de obra"],
    5,
  ),
  svc(
    "pintura",
    "Pintura",
    "Paintbrush",
    "from-pink-500 to-pink-600",
    "Acabados profesionales de pintura interior y exterior con materiales premium y técnicas especializadas.",
    ["Pintura interior", "Pintura exterior", "Revestimientos", "Texturas decorativas"],
    "Pintura y Revestimientos",
    [
      "Preparamos superficies y aplicamos pinturas, revestimientos plásticos, sintéticos y texturas decorativas para interiores y exteriores.",
      "Utilizamos productos de marcas reconocidas con fichas técnicas y colores según carta NCS o RAL.",
    ],
    [
      { title: "Preparación de Superficies", description: "Lijado, empastado, imprimación y tratamiento de humedad." },
      { title: "Protección de Obra", description: "Enmascarado, film y protección de pisos y mobiliario." },
      { title: "Aplicación", description: "Rodillo, soplete o airless según sistema especificado." },
      { title: "Texturas y Detalles", description: "Franjas decorativas, paneles y terminaciones especiales." },
      { title: "Control de Calidad", description: "Uniformidad, espesores y terminación según especificación." },
      { title: "Entrega", description: "Limpieza, retiro de protecciones y acta de conformidad." },
    ],
    [
      { title: "Interiores", items: ["Látex", "Esmaltes", "Antihumedad"] },
      { title: "Exteriores", items: ["SIR", "Siloxano", "Impermeabilizantes"] },
      { title: "Industrial", items: ["Epoxi", "Anticorrosiva", "Señalización"] },
      { title: "Decorativo", items: ["Estuco", "Travertino", "Paneles"] },
    ],
    ["Superficies bien preparadas", "Productos premium", "Colores personalizados", "Obra limpia y protegida"],
    6,
  ),
  svc(
    "viviendas-prefabricadas",
    "Viviendas Prefabricadas",
    "Home",
    "from-teal-500 to-teal-600",
    "Soluciones habitacionales modernas con steel framing, montaje rápido y eficiencia energética.",
    ["Steel framing", "Diseño personalizado", "Montaje rápido", "Eficiencia energética"],
    "Viviendas Prefabricadas y Modulares",
    [
      "Diseñamos y construimos viviendas con sistema steel framing y paneles, reduciendo tiempos de obra y mejorando aislación térmica.",
      "Ideal para vivienda permanente, ampliaciones, oficinas modulares y proyectos en zonas remotas del NOA.",
    ],
    [
      { title: "Anteproyecto", description: "Planos, metrados, presupuesto y selección de terminaciones." },
      { title: "Fabricación", description: "Perfiles galvanizados, paneles y aberturas en taller o sitio." },
      { title: "Fundaciones", description: "Platea, pilotes o bases según estudio de suelo." },
      { title: "Montaje", description: "Armado estructural, cubierta y cerramientos en tiempo récord." },
      { title: "Instalaciones", description: "Electricidad, plomería, gas y aislación completa." },
      { title: "Entrega Llave en Mano", description: "Terminaciones, habilitaciones y garantía estructural." },
    ],
    [
      { title: "Vivienda permanente", items: ["1 a 4 dormitorios", "Cocheras", "Quincho"] },
      { title: "Modular comercial", items: ["Oficinas", "Aulas", "Consultorios"] },
      { title: "Ampliaciones", items: ["Dormitorios", "Depósitos", "Galerías"] },
      { title: "Eficiencia", items: ["Aislación térmica", "Paneles SIP", "LED"] },
    ],
    ["Obra 40% más rápida", "Menor desperdicio de material", "Estructura antisísmica", "Personalización total"],
    7,
  ),
  svc(
    "obras-industriales",
    "Obras Industriales",
    "Factory",
    "from-slate-500 to-slate-600",
    "Proyectos industriales de gran escala: plantas, galpones, naves logísticas e infraestructura agroindustrial.",
    ["Plantas industriales", "Galpones", "Naves logísticas", "Infraestructura"],
    "Ingeniería y Construcción Industrial",
    [
      "Ejecutamos obras industriales con planificación BIM, gestión de seguridad reforzada y coordinación de equipos especializados.",
      "Experiencia en naves, silos, plantas de procesamiento y obras para sector agropecuario e hidrocarburos en el NOA.",
    ],
    [
      { title: "Ingeniería de Detalle", description: "Estructuras metálicas, fundaciones y instalaciones según proceso industrial." },
      { title: "Gestión de Compras", description: "Acero, equipos, logística y control de proveedores críticos." },
      { title: "Obra Civil", description: "Fundaciones, pisos industriales, muros y vías internas." },
      { title: "Montaje Estructural", description: "Armado de nave, grúas, anclajes y soldaduras certificadas." },
      { title: "Instalaciones", description: "Eléctrica, incendio, aire comprimido, agua y desagües industriales." },
      { title: "Puesta en servicio", description: "Pruebas, protocolos de entrega y capacitación operativa." },
    ],
    [
      { title: "Naves y galpones", items: ["Logística", "Depósitos", "Talleres"] },
      { title: "Agroindustria", items: ["Silos", "Acopio", "Secaderos"] },
      { title: "Plantas", items: ["Procesamiento", "Envasado", "Frío industrial"] },
      { title: "Infraestructura", items: ["Camiones de acceso", "Tanques", "Estaciones"] },
    ],
    ["Gestión PMI", "Seguridad industrial reforzada", "Estructuras certificadas", "Cumplimiento normativo sectorial"],
    8,
  ),
  svc(
    "gas",
    "Instalaciones de Gas",
    "Flame",
    "from-red-500 to-red-600",
    "Instalaciones de gas natural, envasado y GLP certificadas por profesionales matriculados con habilitación municipal.",
    ["Gas natural", "Gas envasado", "Calderas", "Certificaciones"],
    "Gas Matriculado y Certificado",
    [
      "Proyectamos e instalamos redes de gas natural, envasado y GLP para viviendas, comercios e industrias con matrícula habilitante.",
      "Realizamos pruebas de estanqueidad, habilitaciones municipales y entrega de certificados exigidos por distribuidoras.",
    ],
    [
      { title: "Relevamiento", description: "Cálculo de consumos, recorrido de cañerías y selección de artefactos." },
      { title: "Proyecto y Trámite", description: "Plano para distribuidora y municipio, gestión de aprobaciones." },
      { title: "Instalación", description: "Cañerías, válvulas, reguladores, artefactos y ventilaciones." },
      { title: "Prueba de Estanqueidad", description: "Ensayo con manómetro, registro fotográfico y acta." },
      { title: "Habilitación", description: "Inspección de distribuidora y entrega de certificado." },
      { title: "Mantenimiento", description: "Revisiones periódicas, conversión de artefactos y reparaciones." },
    ],
    [
      { title: "Gas natural", items: ["Viviendas", "Comercios", "Calderas"] },
      { title: "Gas envasado", items: ["Tanques", "Reguladores", "Cañerías"] },
      { title: "GLP", items: ["Instalaciones industriales", "Restaurantes", "Hoteles"] },
      { title: "Certificaciones", items: ["Habilitación municipal", "Renovaciones", "Inspecciones"] },
    ],
    ["Gasistas matriculados", "Estanqueidad certificada", "Trámites con distribuidora", "Garantía en instalaciones"],
    9,
  ),
]
