import type { SiteService, SiteServiceIconKey } from "@/lib/db/models"
import { getServiceImageAlt } from "@/lib/company/constants"

type ServiceSeed = Omit<SiteService, "_id" | "createdAt" | "updatedAt" | "updatedBy">

function svc(
  slug: string,
  title: string,
  icon: SiteServiceIconKey,
  colorGradient: string,
  shortDescription: string,
  features: string[],
  overviewTitle: string,
  overviewParagraphs: string[],
  processSteps: { title: string; description: string }[],
  workCategories: { title: string; description?: string; items: string[] }[],
  benefits: string[],
  order: number,
): ServiceSeed {
  return {
    slug,
    title,
    icon,
    colorGradient,
    shortDescription,
    features,
    overviewTitle,
    overviewParagraphs,
    processSteps: processSteps.map((s, i) => ({ ...s, order: i + 1 })),
    workCategories,
    benefits,
    heroImage: "",
    heroImageAlt: getServiceImageAlt(title),
    gallery: [],
    published: true,
    order,
  }
}

export const SITE_SERVICE_DEFAULTS: ServiceSeed[] = [
  svc(
    "construccion",
    "Construcción",
    "Building2",
    "from-blue-500 to-blue-600",
    "Construcción residencial, comercial e industrial en el NOA, con planificación, control de obra y entrega documentada según contrato.",
    ["Viviendas unifamiliares", "Edificios comerciales", "Obras públicas", "Estructuras metálicas"],
    "Construcción profesional",
    [
      "Ofrecemos servicios integrales de construcción desde la planificación inicial hasta la entrega final, con un único interlocutor comercial y técnico.",
      "Operamos desde 2018 en Salta, Jujuy, Tucumán y Formosa. El alcance, plazos y garantías de cada obra se definen por escrito en presupuesto y contrato.",
    ],
    [
      { title: "Consulta y planificación", description: "Reunión inicial, relevamiento del sitio, viabilidad, costos y cronograma preliminar." },
      { title: "Diseño y permisos", description: "Planos según proyecto; gestión de permisos cuando el contrato incluye trámites municipales." },
      { title: "Preparación del sitio", description: "Nivelación, excavaciones, cimentaciones y medidas de seguridad." },
      { title: "Estructura", description: "Cimientos, estructura de hormigón y/o acero, muros y techos con controles acordados." },
      { title: "Instalaciones y acabados", description: "Coordinación de gremios: electricidad, sanitarias, gas, pisos, revestimientos y pintura." },
      { title: "Entrega", description: "Inspección conjunta, limpieza, acta de conformidad y documentación pactada en contrato." },
    ],
    [
      { title: "Residencial", items: ["Casas unifamiliares", "Ampliaciones", "Desarrollos habitacionales"] },
      { title: "Comercial", items: ["Oficinas", "Locales comerciales", "Centros comerciales"] },
      { title: "Industrial", items: ["Naves", "Depósitos", "Plantas de producción"] },
      { title: "Institucional", items: ["Educación", "Salud", "Administración pública"] },
    ],
    ["ART verificada antes del ingreso a obra", "Controles en hitos definidos", "Materiales según especificación acordada", "Garantías por escrito según contrato"],
    1,
  ),
  svc(
    "remodelacion",
    "Remodelación",
    "Home",
    "from-purple-500 to-purple-600",
    "Renovación de viviendas, oficinas y locales con diseño acordado, obra ordenada y coordinación de especialidades.",
    ["Remodelación integral", "Ampliaciones", "Refacciones", "Redistribución de ambientes"],
    "Remodelación y renovación",
    [
      "Renovamos espacios existentes respetando la estructura y optimizando la funcionalidad según el proyecto aprobado.",
      "Coordinamos albañilería, electricidad, plomería y pintura bajo un cronograma único para reducir interferencias entre gremios.",
    ],
    [
      { title: "Relevamiento", description: "Visita técnica, mediciones y definición de alcance con el cliente." },
      { title: "Anteproyecto y presupuesto", description: "Propuesta, materiales, plazos y presupuesto por partidas." },
      { title: "Demolición selectiva", description: "Retiro de terminaciones y protección de áreas no intervenidas." },
      { title: "Obra gruesa e instalaciones", description: "Mampostería, ampliaciones y redes según plano." },
      { title: "Terminaciones", description: "Revoques, pisos, carpintería, pintura y detalles." },
      { title: "Entrega", description: "Limpieza, checklist y soporte post-entrega según contrato." },
    ],
    [
      { title: "Viviendas", items: ["Cocinas y baños", "Ampliaciones", "Redistribución"] },
      { title: "Comercios", items: ["Locales", "Gastronomía", "Showrooms"] },
      { title: "Oficinas", items: ["Open space", "Salas de reunión", "Accesibilidad"] },
      { title: "Fachadas", items: ["Revitalización", "Aislación", "Señalética"] },
    ],
    ["Obra protegida y ordenada", "Cronograma acordado por escrito", "Materiales según presupuesto", "Coordinación integral de gremios"],
    2,
  ),
  svc(
    "albanileria",
    "Albañilería",
    "Hammer",
    "from-orange-500 to-orange-600",
    "Mampostería, revoques, contrapisos y hormigón con maestros mayores y control dimensional según plano.",
    ["Mampostería", "Revoques", "Contrapisos", "Hormigón"],
    "Albañilería",
    [
      "Ejecutamos mampostería, revoques, contrapisos y estructuras de hormigón en obra nueva, ampliaciones y reparaciones.",
      "Trabajamos conforme a planos aprobados, con verificación de plomos, niveles y especificaciones del proyecto.",
    ],
    [
      { title: "Replanteo", description: "Trazado y niveles según planos." },
      { title: "Mampostería", description: "Muros portantes, tabiques y ladrillo visto." },
      { title: "Hormigón", description: "Bases, vigas, losas y escaleras." },
      { title: "Revoques", description: "Grueso, fino, interior y exterior." },
      { title: "Contrapisos", description: "Nivelación, aislación y contrapiso." },
      { title: "Control", description: "Verificación dimensional antes de entrega de frente." },
    ],
    [
      { title: "Obra nueva", items: ["Muros", "Tabiques", "Losas"] },
      { title: "Reparaciones", items: ["Grietas", "Humedades", "Refuerzos"] },
      { title: "Revoques", items: ["Exterior", "Texturas", "Ladrillo visto"] },
      { title: "Industrial", items: ["Bases", "Canaletas", "Pisos"] },
    ],
    ["Maestros con experiencia en obra", "Materiales según especificación", "Control de plomos y niveles", "Integración con otros gremios"],
    3,
  ),
  svc(
    "electricidad",
    "Electricidad",
    "Lightbulb",
    "from-yellow-500 to-yellow-600",
    "Instalaciones eléctricas residenciales, comerciales e industriales con materiales homologados y habilitación cuando la normativa lo exige.",
    ["Instalaciones nuevas", "Tableros", "Iluminación", "Trifásica"],
    "Instalaciones eléctricas",
    [
      "Diseñamos e instalamos sistemas eléctricos según carga, normativa AEA aplicable y requisitos del distribuidor o cliente.",
      "La matriculación del responsable técnico y la certificación final dependen del tipo de instalación y jurisdicción; se informan en la propuesta.",
    ],
    [
      { title: "Proyecto", description: "Cálculo de cargas, circuitos y protecciones." },
      { title: "Canalización y cableado", description: "Tendido según plano aprobado." },
      { title: "Tableros", description: "Montaje de protecciones y diferenciales." },
      { title: "Iluminación", description: "Luminarias, sensores y eficiencia acordada." },
      { title: "Pruebas", description: "Continuidad, aislamiento y puesta a tierra." },
      { title: "Documentación", description: "Plano as-built y certificado cuando corresponda por normativa." },
    ],
    [
      { title: "Residencial", items: ["Instalación completa", "Ampliaciones", "Reparaciones"] },
      { title: "Comercial", items: ["Locales", "Oficinas", "Cartelería"] },
      { title: "Industrial", items: ["Trifásica", "Motores", "Tableros"] },
      { title: "Eficiencia", items: ["LED", "Sensores", "Automatización básica"] },
    ],
    ["Responsable técnico según exigencia normativa", "Materiales con respaldo de fabricante", "Mediciones documentadas", "Entrega de documentación cuando aplique"],
    4,
  ),
  svc(
    "plomeria",
    "Plomería",
    "Droplets",
    "from-cyan-500 to-cyan-600",
    "Instalaciones sanitarias, desagües y agua caliente con pruebas de presión y materiales acordados en proyecto.",
    ["Instalaciones sanitarias", "Desagües", "Agua caliente", "Reparaciones"],
    "Plomería y sanitaria",
    [
      "Instalamos y reparamos redes de agua, desagües cloacales y pluviales con materiales seleccionados en presupuesto.",
      "Atendemos refacciones, obras integrales y urgencias según disponibilidad operativa acordada.",
    ],
    [
      { title: "Diagnóstico", description: "Relevamiento de instalaciones existentes." },
      { title: "Proyecto", description: "Dimensionado de cañerías y artefactos." },
      { title: "Instalación", description: "Tendido, conexiones y artefactos." },
      { title: "Pruebas", description: "Presión y estanqueidad documentadas." },
      { title: "Terminaciones", description: "Sellados, griferías y conexiones finales." },
      { title: "Mantenimiento", description: "Planes preventivos bajo contrato de servicio." },
    ],
    [
      { title: "Agua", items: ["Cañerías", "Termotanques", "Bombas"] },
      { title: "Desagües", items: ["Cloacales", "Pluviales"] },
      { title: "Baños y cocinas", items: ["Artefactos", "Mesadas"] },
      { title: "Industrial", items: ["Líneas auxiliares", "Tanques"] },
    ],
    ["Materiales según presupuesto", "Pruebas documentadas", "Atención de urgencias coordinada", "Garantía de mano de obra según contrato"],
    5,
  ),
  svc(
    "pintura",
    "Pintura",
    "Paintbrush",
    "from-pink-500 to-pink-600",
    "Pintura interior y exterior, revestimientos y preparación de superficies según sistema especificado.",
    ["Interior", "Exterior", "Revestimientos", "Texturas"],
    "Pintura y revestimientos",
    [
      "Preparamos superficies y aplicamos sistemas de pintura acordados, con fichas técnicas de producto cuando el cliente lo solicita.",
      "Colores según carta del fabricante o muestra aprobada por el cliente antes de la aplicación general.",
    ],
    [
      { title: "Preparación", description: "Lijado, empastado, imprimación y tratamiento de humedad." },
      { title: "Protección", description: "Enmascarado de pisos y mobiliario." },
      { title: "Aplicación", description: "Rodillo, soplete o airless según sistema." },
      { title: "Detalles", description: "Franjas, paneles y terminaciones especiales." },
      { title: "Control", description: "Uniformidad y terminación acordada." },
      { title: "Entrega", description: "Limpieza y acta de conformidad." },
    ],
    [
      { title: "Interiores", items: ["Látex", "Esmaltes", "Antihumedad"] },
      { title: "Exteriores", items: ["Sistemas impermeables", "Siloxano"] },
      { title: "Industrial", items: ["Epoxi", "Anticorrosiva", "Señalización"] },
      { title: "Decorativo", items: ["Estuco", "Texturas"] },
    ],
    ["Superficies preparadas correctamente", "Productos según especificación", "Colores aprobados por cliente", "Obra protegida y limpia"],
    6,
  ),
  svc(
    "viviendas-prefabricadas",
    "Viviendas Prefabricadas",
    "Home",
    "from-teal-500 to-teal-600",
    "Viviendas y módulos con steel framing u otros sistemas acordados, con plazos y fundaciones según proyecto.",
    ["Steel framing", "Diseño a medida", "Montaje en sitio", "Aislación térmica"],
    "Viviendas prefabricadas y modulares",
    [
      "Diseñamos y construimos soluciones habitacionales y modulares con sistema acordado en anteproyecto (steel framing, paneles, etc.).",
      "Los plazos de montaje y requisitos estructurales dependen del diseño, suelo y normativa local; se detallan en la propuesta.",
    ],
    [
      { title: "Anteproyecto", description: "Planos, metrados, presupuesto y terminaciones." },
      { title: "Fabricación", description: "Perfiles, paneles y aberturas según diseño." },
      { title: "Fundaciones", description: "Platea, pilotes o bases según estudio de suelo." },
      { title: "Montaje", description: "Armado estructural, cubierta y cerramientos." },
      { title: "Instalaciones", description: "Electricidad, plomería, gas y aislación." },
      { title: "Entrega", description: "Terminaciones, habilitaciones y documentación pactada." },
    ],
    [
      { title: "Vivienda", items: ["1 a 4 dormitorios", "Cocheras", "Quincho"] },
      { title: "Modular comercial", items: ["Oficinas", "Aulas", "Consultorios"] },
      { title: "Ampliaciones", items: ["Dormitorios", "Depósitos"] },
      { title: "Eficiencia", items: ["Aislación", "Paneles", "Iluminación LED"] },
    ],
    ["Plazos acordados por escrito", "Menor interferencia en sitio ocupado", "Diseño según normativa del proyecto", "Personalización en anteproyecto"],
    7,
  ),
  svc(
    "obras-industriales",
    "Obras Industriales",
    "Factory",
    "from-slate-500 to-slate-600",
    "Naves, galpones, plantas e infraestructura agroindustrial con planificación, SST reforzada y entregables según contrato.",
    ["Naves y galpones", "Agroindustria", "Plantas", "Infraestructura"],
    "Construcción industrial",
    [
      "Ejecutamos obras industriales con ingeniería de detalle, gestión de compras críticas y coordinación de montaje estructural.",
      "La experiencia por sector (agro, logística, procesamiento) se acredita con referencias de obra publicadas o documentación bajo solicitud.",
    ],
    [
      { title: "Ingeniería de detalle", description: "Estructuras, fundaciones e instalaciones según proceso." },
      { title: "Compras", description: "Acero, equipos y logística acordada." },
      { title: "Obra civil", description: "Fundaciones, pisos industriales y vías internas." },
      { title: "Montaje", description: "Estructura metálica, anclajes y soldaduras según especificación." },
      { title: "Instalaciones", description: "Eléctrica, incendio, aire, agua y desagües industriales." },
      { title: "Puesta en marcha", description: "Pruebas y protocolos acordados con el cliente." },
    ],
    [
      { title: "Naves", items: ["Logística", "Depósitos", "Talleres"] },
      { title: "Agroindustria", items: ["Silos", "Acopio", "Secaderos"] },
      { title: "Plantas", items: ["Procesamiento", "Envasado"] },
      { title: "Infraestructura", items: ["Accesos", "Tanques", "Estaciones"] },
    ],
    ["Cronograma y hitos en contrato", "SST reforzada en obra industrial", "Soldaduras según especificación", "Cumplimiento normativo del sector contratado"],
    8,
  ),
  svc(
    "gas",
    "Instalaciones de Gas",
    "Flame",
    "from-red-500 to-red-600",
    "Instalaciones de gas natural, envasado y GLP con gasista matriculado y habilitación cuando la normativa y el distribuidor lo exigen.",
    ["Gas natural", "Gas envasado", "Calderas", "Habilitaciones"],
    "Instalaciones de gas",
    [
      "Proyectamos e instalamos redes de gas para viviendas, comercios e industrias con profesional habilitado según jurisdicción.",
      "Las pruebas de estanqueidad, trámites ante distribuidora y certificados se gestionan cuando el tipo de instalación lo requiere.",
    ],
    [
      { title: "Relevamiento", description: "Consumos, recorrido y selección de artefactos." },
      { title: "Proyecto y trámite", description: "Plano y gestión ante distribuidora/municipio si aplica." },
      { title: "Instalación", description: "Cañerías, válvulas, reguladores y ventilaciones." },
      { title: "Estanqueidad", description: "Ensayo con registro según procedimiento." },
      { title: "Habilitación", description: "Inspección de distribuidora cuando corresponda." },
      { title: "Mantenimiento", description: "Revisiones periódicas bajo contrato." },
    ],
    [
      { title: "Gas natural", items: ["Viviendas", "Comercios", "Calderas"] },
      { title: "Gas envasado", items: ["Tanques", "Reguladores"] },
      { title: "GLP", items: ["Comercial", "Gastronomía"] },
      { title: "Trámites", items: ["Habilitación", "Renovaciones"] },
    ],
    ["Gasista habilitado según normativa local", "Prueba de estanqueidad documentada", "Trámites coordinados con distribuidora", "Garantía según contrato y normativa"],
    9,
  ),
]
