import type { LucideIcon } from "lucide-react"
import {
  LayoutDashboard,
  FolderKanban,
  FileText,
  HardHat,
  ClipboardList,
  CheckSquare,
  BookOpen,
  Search,
  ListChecks,
  HelpCircle,
  Calendar,
  Users,
  Mail,
  DollarSign,
  Receipt,
  CreditCard,
  FileSignature,
  UserCog,
  Truck,
  Package,
  AlertTriangle,
  Award,
  Globe,
  ImageIcon,
  Settings,
  Shield,
  BarChart3,
  Wallet,
} from "lucide-react"
import type { DashboardNavGroup } from "@/lib/dashboard/navigation"

/** Navegación completa — admin, super_admin y gerente (filtrada por permisos). */
export const MANAGEMENT_NAV_GROUPS: DashboardNavGroup[] = [
  {
    id: "obras",
    label: "Obras",
    icon: HardHat,
    items: [
      { name: "Proyectos", href: "/dashboard/proyectos", icon: FolderKanban, permission: "projects.view" },
      { name: "Nuevo proyecto", href: "/dashboard/proyectos/nuevo", icon: FolderKanban, permission: "projects.create" },
      { name: "Cumplimiento de obra", href: "/dashboard/cumplimiento-obra", icon: ClipboardList, permission: "compliance.manage" },
      { name: "Tareas", href: "/dashboard/tareas", icon: CheckSquare, permission: "tasks.view" },
      { name: "Bitácora diaria", href: "/dashboard/bitacora-diaria", icon: BookOpen, permission: "daily_logs.view" },
      { name: "Inspecciones", href: "/dashboard/inspecciones", icon: Search, permission: "inspections.view" },
      { name: "Punch lists", href: "/dashboard/punch-lists", icon: ListChecks, permission: "quality.view" },
      { name: "RFIs", href: "/dashboard/rfis", icon: HelpCircle, permission: "documents.view" },
      { name: "Calendario", href: "/dashboard/calendario", icon: Calendar, permission: "calendar.view" },
      { name: "Documentos", href: "/dashboard/documentos", icon: FileText, permission: "documents.view" },
    ],
  },
  {
    id: "comercial",
    label: "Comercial",
    icon: Users,
    items: [
      { name: "Clientes", href: "/dashboard/clientes", icon: Users, permission: "clients.view" },
      { name: "Cotizaciones", href: "/dashboard/cotizaciones", icon: FileText, permission: "finance.view" },
      { name: "Consultas web", href: "/dashboard/contactos", icon: Mail, permission: "contacts.view" },
      { name: "Contratos", href: "/dashboard/contratos", icon: FileSignature, permission: "finance.view" },
    ],
  },
  {
    id: "finanzas",
    label: "Finanzas",
    icon: DollarSign,
    items: [
      { name: "Finanzas", href: "/dashboard/finanzas", icon: DollarSign, permission: "finance.view" },
      { name: "Facturas", href: "/dashboard/facturas", icon: Receipt, permission: "finance.view" },
      { name: "Pagos", href: "/dashboard/pagos", icon: CreditCard, permission: "finance.view" },
    ],
  },
  {
    id: "recursos",
    label: "Recursos",
    icon: UserCog,
    items: [
      { name: "Empleados", href: "/dashboard/empleados", icon: UserCog, permission: "employees.view" },
      { name: "Proveedores", href: "/dashboard/proveedores", icon: Truck, permission: "suppliers.view" },
      { name: "Inventario", href: "/dashboard/inventario", icon: Package, permission: "inventory.view" },
    ],
  },
  {
    id: "calidad",
    label: "Calidad y SST",
    icon: Shield,
    items: [
      { name: "Incidencias", href: "/dashboard/incidencias", icon: AlertTriangle, permission: "incidents.view" },
      { name: "Certificados", href: "/dashboard/certificados", icon: Award, permission: "certificates.view" },
      { name: "Línea de ética", href: "/dashboard/linea-etica", icon: Shield, permission: "incidents.view" },
    ],
  },
  {
    id: "sitio-web",
    label: "Sitio web",
    icon: Globe,
    items: [
      { name: "Servicios públicos", href: "/dashboard/sitio-web/servicios", icon: Globe, permission: "website.view" },
      { name: "Proyectos públicos", href: "/dashboard/sitio-web/proyectos", icon: ImageIcon, permission: "website.view" },
      { name: "Portadas y sliders", href: "/dashboard/sitio-web/paginas", icon: LayoutDashboard, permission: "website.edit" },
    ],
  },
  {
    id: "portal-admin",
    label: "Portal empleados",
    icon: Wallet,
    items: [
      { name: "Administración portal", href: "/dashboard/admin/portal", icon: Wallet, permission: "portal.admin" },
    ],
  },
  {
    id: "sistema",
    label: "Sistema",
    icon: Settings,
    items: [
      { name: "Usuarios", href: "/dashboard/usuarios", icon: Users, permission: "users.view" },
      { name: "Roles", href: "/dashboard/roles", icon: Shield, permission: "admin.roles" },
      { name: "Accesos pendientes", href: "/dashboard/accesos", icon: UserCog, permission: "users.view" },
      { name: "Auditoría", href: "/dashboard/auditoria", icon: Search, permission: "admin.logs" },
      { name: "Reportes", href: "/dashboard/reportes", icon: BarChart3, permission: "reports.view" },
      { name: "Configuración", href: "/dashboard/configuracion", icon: Settings, permission: "admin.settings" },
    ],
  },
]
